### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by aphilsmith** [aykutalparslan/Telegram-Server#28]
There are no build notes.

**Comment by aykutalparslan** [comment]
You would need a working Cassandra install
then

git clone https://github.com/aykutalparslan/Telegram-Server
cd Telegram-Server
gradlew
gradlew build
java -jar build/libs/TelegramServer-0.1.jar

**Comment by aphilsmith** [comment]
Thanks! How would I configure a Telegram windows client to use this server?

**Comment by aykutalparslan** [comment]
Unfortunately project currently does not implement the full and intermediate versions of the protocol. Windows client would not work. Mobile clients worked to some degree(chats,group chats, secret chats worked with bugs) while I was maintaning the code but I have not tested the code since last commit. In its current state project needs at least six months of development which I do not have time for.
